# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Seonghun Son
# Description of the Site
description: Ph.D Student at Iowa State University
# URL of Image of the Site
site-image: '/assets/images/meta.jpg'
# Keywords of the Sites
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: 'https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
#heroimage: '/assets/images/particle.jpg'

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: seonghunie@gmail.com
facebook_username: seonghunie
#twitter_username: thedevslot
instagram_username: hunie_son_
linkedin_username: /in/seonghun-son-665924152/
github_username:  hunie-som
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Seonghun Son

# Name of the Author
author-name: Seonghun Son
# URL for the Image of the Author
author-image: 'https://github.com/hunie-son/hunie-son.github.io/blob/main/assets/images/VIsa_Photo.jpg'
# 60 Words About the Author
author-about: I graduated from Yeungnam University majored in Information and Communication Engineering. I was a member of the Functional Safety Team(SW part) at SL Corporation. And also Assistant Manager at ICT Infrastructure Strategy and Planning Team, National Information Society Agency(NIA). Currently, I am doing a Ph.D. course at Iowa State University.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url:

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
